### ISSUE TITLE
clip_by_cn_border

### ISSUE THREAD

**Issue by Aqi-MH13** [ZhaJiMan/frykit#1]
使用clip_by_cn_border（）会出现draw_artist can only be used after an initial draw which caches the renderer，是什么原因呢

**Comment by ZhaJiMan** [comment]
能展示一下完整的代码，matplotlib 和 cartopy 的版本吗？

**Comment by Aqi-MH13** [comment]
运行的代码是您的contourf.py     matplotlib=3.4.3        cartopy=0.20.0

**Comment by ZhaJiMan** [comment]
当 Matplotlib < 3.6.0 时就会出现这个问题，我按问题更新了一下包，你可以 pip install frykit=0.2.1 试试

**Comment by Aqi-MH13** [comment]
谢谢作者，问题已经解决了，工具包非常好用，祝越来越好！！！！
