### ISSUE TITLE
无法使用fplt.clip_by_cn_province对特定省份进行裁剪

### ISSUE THREAD

**Issue by donglx2018** [ZhaJiMan/frykit#10]
程序运行发生错误，根据错误提示发现shp.py中第611行的命令似乎有错误，具体如下。
![image](https://github.com/user-attachments/assets/d05a4192-e061-455c-a1e3-6f247fbfb855)

**Comment by ZhaJiMan** [comment]
给下 matplotlib 和 frykit 版本，以及更完整的代码示例

**Comment by donglx2018** [comment]
> 给下 matplotlib 和 frykit 版本，完整的代码示例，以及报错信息

matplotlib3.4.3、frykit0.6.8.

**Comment by ZhaJiMan** [comment]
草，才发现是单词拼错了，多谢指出。你改下源码就能正常运行了。

**Comment by donglx2018** [comment]
> 给下 matplotlib 和 frykit 版本，完整的代码示例，以及报错信息

matplotlib3.4.3、frykit0.6.8。
将shp.py中第611行的“apend”修改为“append”后，问题已解决。

**Comment by ZhaJiMan** [comment]
上传修改了拼写的 0.6.9 版本

```bash
pip install frykit -U
```

即可。就裁剪测试了内置的所有省市，现在没问题了。
