### ISSUE TITLE
制作南海掩膜

### ISSUE THREAD

**Issue by yliu-yb** [ZhaJiMan/frykit#11]
能实现制作南海的掩膜吗？

**Comment by ZhaJiMan** [comment]
需要描述南海轮廓的坐标数组，如果是 matplotlib 视觉上抠出南海，可以用 `fplt.clip_by_polygon`。如果是数据上想保留落入南海内的数据点，可以用 geopandas、`shapely.vectorized.contains` 等函数。

**Comment by yliu-yb** [comment]
> 需要描述南海轮廓的坐标数组，如果是 matplotlib 视觉上抠出南海，可以用 `fplt.clip_by_polygon`。如果是数据上想保留落入南海内的数据点，可以用 geopandas、`shapely.vectorized.contains` 等函数。

请问frykit带有南海轮廓的坐标数组吗？

**Comment by ZhaJiMan** [comment]
没有，需要自行准备 geojson、shapefile 之类的文件。
（其实我也不知道南海具体是指什么范围）
