### ISSUE TITLE
投影相关

### ISSUE THREAD

**Issue by Curallin** [ZhaJiMan/frykit#12]
请问如果栅格数据坐标系不是WGS84，比如投影坐标系，能否使用fplt.clip_by_cn_border()等这些函数

**Comment by ZhaJiMan** [comment]
`fplt.clip_by_cn_border` 函数能自动根据 `GeoAxes.projection`，对 `Artist` 进行裁剪。
它并不直接作用于你的栅格数据，栅格数据的投影由用户在画图前手动处理（pyproj、geopandas 等），或者用 cartopy 画图时通过指定 `transform` 参数自动处理。

**Comment by Curallin** [comment]
请问您的意思是直接用该函数，得要手动处理栅格数据的投影到和GeoAxes.projection保持一致对吗

**Comment by Curallin** [comment]
比如说在ax.imshow()中的transform参数传入栅格数据的crs对吗？受教了！

**Comment by Curallin** [comment]
您的包非常的好用，本来用cnmaps的，但是它跟很多包冲突了，于是现在直接用您的包绘图。不过使用过程中有些小小的建议，如果您有精力调整一下，我觉得就非常完美了。
1.fplt.add_countries中能否设置成和fplt.add_cn_province一样，通过一个列表，可以把几个国家的地图绘制显示出来。我想对您来说很简单，原理是适用的
2.绘制的比例尺能否用matplotlib里面的patch做一下处理，有那种和GIS软件里面类似的黑白相间的矩形框这种样式就再好不过了，您使用GMT风格边框时应该用到了，这点您应该也可以实现
3.是否可以更改一些省份的标签，不仅仅是添加省名，还可以添加数据，有时候我们可能想绘制一些数据的全国分布图。
我会在公众号强烈推荐您的包，现在已经非常完美了，如果这些小小的细节能够再完善一下，我觉得可以算是国内适配matplotlib和cartopy最好用的绘图包了。

**Comment by ZhaJiMan** [comment]
1. 这个 [issue](https://github.com/ZhaJiMan/frykit/issues/8) 里提到了为什么国家无法指定，因为我还不确定用什么名字来索引国家。

2. 黑白矩形框的比例尺算隐藏功能吧，不太完善所以没列在 README 里。
```python
import numpy as np
import matplotlib.pyplot as plt
import frykit.plot as fplt

ax = plt.axes(projection=fplt.PLATE_CARREE)
ax.stock_img()
fplt.set_map_ticks(ax, (70, 140, 0, 60))
scale_bar = fplt.add_scale_bar(ax, 0.65, 0.1, length=2000)
scale_bar.set_xticks(np.linspace(0, 2000, 5))
scale_bar.tick_params(labelsize='x-small')
fplt.add_frame(scale_bar)
```

![image](https://github.com/user-attachments/assets/b99cfd00-ee1d-4bb4-9cfa-3d0ccd4073e5)

3. 不用省名而是用数据：

- 用户自己准备经纬度，循环用 `Axes.text` 加。
- 用行政区划的多边形计算出一个经纬度，比如说用 shapely 或 geopandas 的 `representative_point`
- 用 frykit 拿来标省市县名称的经纬度

```python
import frykit.shp as fshp

df = fshp.get_cn_province_table()
fplt.add_texts(ax, df['lon'], df['lat'], data)
```

cnmaps 我感觉是被上游的 shapely 给坑了，详见这个 [issue](https://github.com/cnmetlab/cnmaps/issues/106)，导致其它包的版本也被低版本的 shapely 限制了，无法跟上最新的 python 生态。

感谢公众号推荐。

**Comment by Curallin** [comment]
非常感谢 祝您科研顺利！

**Comment by Curallin** [comment]
求问博主这种情况是怎么回事，我已经将数据投影中的transform参数设置成了数据的投影，但是出现了这种问题

![Image](https://github.com/user-attachments/assets/128cfe32-683f-418e-af7a-53667cf2d3b8)

**Comment by ZhaJiMan** [comment]
报错看不全

**Comment by Curallin** [comment]
不好意思，我那个问题好像换了个方法解决了，记不起来了。我想请教一下您，就是比例尺的粗细如何调整，我的figsize设置的很大的时候，这时候感觉比例尺太细了点😂

![Image](https://github.com/user-attachments/assets/f026f6ca-ca42-4715-a13e-41d5352cc5cf)

如何修改下面这段控制比例尺的代码捏，我感觉是不是应该在scale_bar上动点手脚，想请问一下您
![Image](https://github.com/user-attachments/assets/d6e3fdcc-2223-47ea-8ec7-7a6897e1bf86)

**Comment by ZhaJiMan** [comment]
如果是图中这个样式的话，`fplt.add_frame` 有个 `width` 参数可以让比例尺更厚一点

**Comment by Curallin** [comment]
好的好的 非常感谢您 这样确实可以加宽🙌
