### ISSUE TITLE
墨卡托投影绘图问题

### ISSUE THREAD

**Issue by sunhuihang** [ZhaJiMan/frykit#2]
使用conturf脚本，只将map_crs 改为ccrs.Mercator(central_longitude=105) ，使用墨卡托投影，会产生问题
绘图如下
![image](https://github.com/ZhaJiMan/frykit/assets/56792866/37e167aa-30f2-46c8-80f3-c5859ee895ce)

**Comment by sunhuihang** [comment]
奥奥 不对，不能设置中心经度为105°，这好像使海陆mask产生了偏移，要设置为0

**Comment by ZhaJiMan** [comment]
`add_land` 和 `add_countries` 使用的数据范围涉及全球，当 `PlateCarree` 或 `Mercator` 投影的中心经度为 0 度以外的其它值时，投影坐标系的边界就不再是正负 180 度了，此时直接使用 pyproj 做变换会产生错误的结果。所以并不是产生偏移，而是投影过程中没有正确处理好跨越边界的几何图形。

解决方法就是中心经度始终设为 0 度。实际上如果你不是想画一张中心不在本初子午线的全球地图，而只是选世界上某个区域来画的话，中心经度设为 0 度就 OK。例子里的等距方位投影则是必须设置中心经度，否则无法将中国置于地图中心。
