### ISSUE TITLE
【分省填色】例子里，内蒙最东北边为什么有一块黑龙江的地？shp问题？

### ISSUE THREAD

**Issue by ybmy001** [ZhaJiMan/frykit#5]
如题。

**Comment by ZhaJiMan** [comment]
你是指加格达奇区吗，是黑龙江在内蒙古境内的飞地，可以参考这个视频
https://www.bilibili.com/video/BV1CK411V7j3

**Comment by ybmy001** [comment]
OK。第一次听到“飞地”这个词。昨天刚好也打开了百度地图看了下，没看到这个区域。现在了解了
