### ISSUE TITLE
炸鸡资源

### ISSUE THREAD

**Issue by nickbsb** [ZhaJiMan/frykit#7]
老师您好，问下怎么看到您博客中的各种炸鸡资源？是输入什么密码吗？

**Comment by nickbsb** [comment]
老师，公众号叫气象备忘录是吗？我回复您了

**Comment by ZhaJiMan** [comment]
无资源，那个是纯整蛊页面

**Comment by nickbsb** [comment]
哦，气象备忘录是您的公众号吗？

**Comment by ZhaJiMan** [comment]
不是，是 [jiaobf](https://github.com/jiaobf) 兄的账号，我只是偶尔会投稿而已，我没有公众号只有博客。
博客问题可以在博客留言，包的问题可以在 issue 页面留言，邮箱留言也可以。公众号留言的话我一般看不到。
