### ISSUE TITLE
大佬，请教一个问题，如何获取全球各国对应的shp

### ISSUE THREAD

**Issue by shanchuanxiao** [ZhaJiMan/frykit#8]
我看您的库里面fshp.get_countries()能够获取全球的国界线，那可以像获取中国省界那样根据国名获取对应国家的边界吗？
感谢你的解答！

**Comment by ZhaJiMan** [comment]
目前不能。

这个数据是 [MeteoInfo](http://www.meteothink.org/) map 目录里的 `country.shp`，中国部分带台湾，并且阿克赛钦和藏南部分没有缺失，但数据似乎挺老的。

我加到库里只是为了方便画世界国界，只提取了原文件的坐标数据，没有保留字段信息。

可以加这个功能，但我不确定该用什么什么关键词来查询。英文国名？中文国名？国家代码？这块我不太熟。
